services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowio_frontend_container
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
