# Generated by Django 5.1.3 on 2025-03-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradient_theme', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Background Workspace',
                'verbose_name_plural': 'Background Workspaces',
            },
        ),
    ]
