# Generated by Django 5.1.3 on 2025-03-25 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('background_workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('background_workspace_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_workspaces_background_workspace', to='background_workspaces.backgroundworkspace')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_workspaces_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
            },
        ),
    ]
